### ISSUE TITLE
[FEATURE] 포인트 환전 관련 프론트 페이지 작업

### ISSUE THREAD

**Issue by bongsh0112** [donsonioc2010/picasso#45]
포인트 환전 관련 프론트 페이지 작업

## 🌲 TODO
- [x] 환전 메인 페이지
- [x] 카카오페이 / 토스페이 선택 모달창
- [x] 이미지가 없는 경우 메인페이지 슬라이드 크기 유지
- [x] 푸터 위치 고정(min-height 위치고정)
