### ISSUE TITLE
[FEATURE] 환전 페이지 ui 작업 + 환전 API 리팩토링

### ISSUE THREAD

**Issue by bongsh0112** [donsonioc2010/picasso#61]
## 🌲TODO

- [x] 결제 성공 / 실패 상태페이지
- [x] 결제 성공 / 실패 후 마이페이지로 리다이렉트
- [ ] 환전 API 리팩토링
